FROM datadog/agent:7

ENV DD_APM_ENABLED=true
ENV NON_LOCAL_TRAFFIC=true
ENV DD_APM_NON_LOCAL_TRAFFIC=true
ENV DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
#ENV DD_HOSTNAME=datadog-agent.railway.internal
ENV DD_OPENAI_LOGS_ENABLED=1

ARG DD_API_KEY
